// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentSystem.Data;

#nullable disable

namespace RecruitmentSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250204051904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentSystem.Models.EmployeesModel", b =>
                {
                    b.Property<int>("Pk_emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pk_emp_id"));

                    b.Property<string>("EmpContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpDesignation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Emp_joining_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Pk_emp_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.SkillsModel", b =>
                {
                    b.Property<int>("pk_skills_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_skills_id"));

                    b.Property<bool>("is_min_req_skills")
                        .HasColumnType("bit");

                    b.Property<string>("skills_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("skills_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pk_skills_id");

                    b.ToTable("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
