// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentSystem.Data;

#nullable disable

namespace RecruitmentSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250210104754_UpdateSchema")]
    partial class UpdateSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentSystem.Models.ApplicationModel", b =>
                {
                    b.Property<int>("pk_application_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_application_id"));

                    b.Property<int>("applicationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("application_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fk_candidate_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_position_id")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pk_application_id");

                    b.HasIndex("fk_candidate_id");

                    b.HasIndex("fk_position_id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.CandidateModel", b =>
                {
                    b.Property<int>("pk_candidate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_candidate_id"));

                    b.Property<string>("candidate_contact_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("candidate_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("candidate_linkdien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("candidate_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("candidate_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pk_candidate_id");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.DocuementModel", b =>
                {
                    b.Property<int>("pk_document_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_document_id"));

                    b.Property<string>("document_file_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("document_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("document_verification_status")
                        .HasColumnType("bit");

                    b.Property<int>("fk_candidate_id")
                        .HasColumnType("int");

                    b.Property<int?>("fk_emp_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("uploaded_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("verified_at")
                        .HasColumnType("datetime2");

                    b.HasKey("pk_document_id");

                    b.HasIndex("fk_candidate_id");

                    b.HasIndex("fk_emp_id");

                    b.ToTable("Docuements");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.EmpRoleMapModel", b =>
                {
                    b.Property<int>("pk_role_map_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_role_map_id"));

                    b.Property<int>("fk_emp_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_role_id")
                        .HasColumnType("int");

                    b.HasKey("pk_role_map_id");

                    b.HasIndex("fk_emp_id");

                    b.HasIndex("fk_role_id");

                    b.ToTable("RolesMap");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.EmployeesModel", b =>
                {
                    b.Property<int>("pk_emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_emp_id"));

                    b.Property<string>("emp_contact_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("emp_joining_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("emp_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pk_emp_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.InterviewPanelModel", b =>
                {
                    b.Property<int>("pk_interview_panel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_interview_panel_id"));

                    b.Property<int?>("employeespk_emp_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_emp_interview_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_position_interview_id")
                        .HasColumnType("int");

                    b.Property<int?>("positionpk_position_id")
                        .HasColumnType("int");

                    b.HasKey("pk_interview_panel_id");

                    b.HasIndex("employeespk_emp_id");

                    b.HasIndex("positionpk_position_id");

                    b.ToTable("InterviewPanelModel");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.PositionModel", b =>
                {
                    b.Property<int>("pk_position_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_position_id"));

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fk_candidate_key")
                        .HasColumnType("int");

                    b.Property<int>("fk_emp_id")
                        .HasColumnType("int");

                    b.Property<int>("is_open")
                        .HasColumnType("int");

                    b.Property<DateTime>("position_creation_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("position_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position_level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position_min_experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary_range")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pk_position_id");

                    b.HasIndex("fk_candidate_key")
                        .IsUnique()
                        .HasFilter("[fk_candidate_key] IS NOT NULL");

                    b.HasIndex("fk_emp_id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.PositionSkillMapModel", b =>
                {
                    b.Property<int>("pk_position_skill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_position_skill_id"));

                    b.Property<int>("fk_position_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_skills_id")
                        .HasColumnType("int");

                    b.HasKey("pk_position_skill_id");

                    b.HasIndex("fk_position_id");

                    b.HasIndex("fk_skills_id");

                    b.ToTable("PositionSkillMap");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.ReviewerPanelModel", b =>
                {
                    b.Property<int>("pk_reviwer_panel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_reviwer_panel_id"));

                    b.Property<int?>("employeespk_emp_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_emp_review_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_position_review_id")
                        .HasColumnType("int");

                    b.Property<int?>("positionpk_position_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("review_deadline")
                        .HasColumnType("datetime2");

                    b.HasKey("pk_reviwer_panel_id");

                    b.HasIndex("employeespk_emp_id");

                    b.HasIndex("positionpk_position_id");

                    b.ToTable("ReviewerPanelModel");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.RoleModel", b =>
                {
                    b.Property<int>("pk_role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_role_id"));

                    b.Property<string>("role_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pk_role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.SkillsModel", b =>
                {
                    b.Property<int>("pk_skills_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pk_skills_id"));

                    b.Property<bool>("is_min_req_skills")
                        .HasColumnType("bit");

                    b.Property<string>("skills_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("skills_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pk_skills_id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.ApplicationModel", b =>
                {
                    b.HasOne("RecruitmentSystem.Models.CandidateModel", "candidate")
                        .WithMany("Applications")
                        .HasForeignKey("fk_candidate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentSystem.Models.PositionModel", "position")
                        .WithMany("Applications")
                        .HasForeignKey("fk_position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("candidate");

                    b.Navigation("position");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.DocuementModel", b =>
                {
                    b.HasOne("RecruitmentSystem.Models.CandidateModel", "candidate")
                        .WithMany("Document")
                        .HasForeignKey("fk_candidate_id");

                    b.HasOne("RecruitmentSystem.Models.EmployeesModel", "employees")
                        .WithMany("Document")
                        .HasForeignKey("fk_emp_id");

                    b.Navigation("candidate");

                    b.Navigation("employees");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.EmpRoleMapModel", b =>
                {
                    b.HasOne("RecruitmentSystem.Models.EmployeesModel", "Employees")
                        .WithMany("RoleMap")
                        .HasForeignKey("fk_emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentSystem.Models.RoleModel", "Role")
                        .WithMany("RoleMap")
                        .HasForeignKey("fk_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employees");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.InterviewPanelModel", b =>
                {
                    b.HasOne("RecruitmentSystem.Models.EmployeesModel", "employees")
                        .WithMany("Interviews")
                        .HasForeignKey("employeespk_emp_id");

                    b.HasOne("RecruitmentSystem.Models.PositionModel", "position")
                        .WithMany("Interviews")
                        .HasForeignKey("positionpk_position_id");

                    b.Navigation("employees");

                    b.Navigation("position");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.PositionModel", b =>
                {
                    b.HasOne("RecruitmentSystem.Models.CandidateModel", "Candidate")
                        .WithOne("Position")
                        .HasForeignKey("RecruitmentSystem.Models.PositionModel", "fk_candidate_key");

                    b.HasOne("RecruitmentSystem.Models.EmployeesModel", "Employees")
                        .WithMany("positions")
                        .HasForeignKey("fk_emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.PositionSkillMapModel", b =>
                {
                    b.HasOne("RecruitmentSystem.Models.PositionModel", "Position")
                        .WithMany("PositionSkill")
                        .HasForeignKey("fk_position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentSystem.Models.SkillsModel", "Skills")
                        .WithMany("PositionSkill")
                        .HasForeignKey("fk_skills_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.ReviewerPanelModel", b =>
                {
                    b.HasOne("RecruitmentSystem.Models.EmployeesModel", "employees")
                        .WithMany("Reviews")
                        .HasForeignKey("employeespk_emp_id");

                    b.HasOne("RecruitmentSystem.Models.PositionModel", "position")
                        .WithMany("Reviews")
                        .HasForeignKey("positionpk_position_id");

                    b.Navigation("employees");

                    b.Navigation("position");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.CandidateModel", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Document");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.EmployeesModel", b =>
                {
                    b.Navigation("Document");

                    b.Navigation("Interviews");

                    b.Navigation("Reviews");

                    b.Navigation("RoleMap");

                    b.Navigation("positions");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.PositionModel", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Interviews");

                    b.Navigation("PositionSkill");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.RoleModel", b =>
                {
                    b.Navigation("RoleMap");
                });

            modelBuilder.Entity("RecruitmentSystem.Models.SkillsModel", b =>
                {
                    b.Navigation("PositionSkill");
                });
#pragma warning restore 612, 618
        }
    }
}
